---
title: "Lab4 grade analysis"
author: Damiche Inès
format: html
editor: visual
---

# Preparation 
```{r}
#| message: FALSE
here::i_am("r-101-grade-analysis.Rproj")
library(here)
library(vroom)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
theme_set(theme_bw())
```

# Question 1 
```{r}
#| message: FALSE
grades <- vroom(here("grades.csv"))
```
# Question 2
```{r}
#| message: FALSE
grades |> 
  filter(!is.na(Exam))|> 
  summarise( min = min(Exam), max = max(Exam), median = median(Exam), mean = mean(Exam))|> 
  knitr::kable()
  
```

# Question 3
```{r}
 nb_na <- sum(is.na(grades$Exam))
```

`r nb_na` students did not take the final exam.

# Question 4

```{r}
#| message: FALSE
grades |> 
  filter(!is.na(Exam))|> 
  ggplot(aes(x = Exam), is.na = TRUE)+ geom_histogram()
```

# Question 5 

```{r}
count_grp <- 
  grades |> 
  group_by(Group) |>
  summarise(count = n())
knitr::kable(count_grp)
```
# Question 6 

```{r}
ggplot(count_grp, aes(x= Group, y = count))+
  geom_point()+
  theme(axis.text.x=element_text(size=4.5))
  
```

# Question 7 

## Method 1 
```{r}
#We take the average grade for each group
grades |> 
  group_by(Group) |>  
  filter(!is.na(Exam))|>
  summarise(mean = mean(Exam))|>
  ggplot(aes(x= Group, y = mean)) + geom_point()+
  theme(axis.text.x=element_text(size=4.5))

```

## Method 2

```{r}
grades |> 
  filter(!is.na(Exam))|>
  ggplot(aes(x = Exam))+
  geom_bar()+
  facet_wrap(~Group)
  
```

# Question 8 
```{r}
group_na <- 
  grades |>                                    
  group_by(Group) |>
  summarize(na_count = sum(is.na(Exam)))
```

# Question 9 

```{r}
ggplot(group_na, aes(x = Group, y = na_count))+ geom_col() + theme(axis.text.x=element_text(size=4.5))
```
# Question 10 

```{r}
options(digits = 3)
new_df <- 
  pivot_longer(grades, cols= c(Exam, starts_with("MCQ"), starts_with("Online")), names_to = "name", values_to = "value")
  
```

# Question 11

```{r}
na_student <- 
  new_df |>
  group_by(Id) |>
  summarise(na_count = sum(is.na(value)))
```

# Question 12

```{r}
ggplot(na_student, aes(x = Id, y = na_count)) + stat_bin_hex()
```
# Question 13 

```{r}
new_df |> 
  filter(name == 'Exam') |>
  group_by(Group) |>
  summarize(na_count = sum(is.na(value))) |>
  knitr::kable()
```


# Question 14

```{r}
id_na_online <- 
  new_df |> 
  filter(str_starts(name, "Online")) |>
  group_by(Id) |>
  summarize(na_count = sum(is.na(value))) 
```
# Question 15 

```{r}
#| message: FALSE
# Step 1: I want to add a column to the previous table with the exam grade for each student 

# I sort the grades data base to be able to take the Exam column and add it to the previous table in order to create a new table with all the information we need
grades_arranged <- 
  grades |>
  arrange(Id)

id_na_online_bis <- data_frame(id_na_online, exam_grade = grades_arranged$Exam)
  

# Step 2: When several students have the same number of NA, I take the mean of their grades 
id_na_online_bis |>
  filter(!is.na(exam_grade))|>
  group_by(na_count) |>
  summarize(mean_exam_grade = mean(exam_grade))|>
  # Step 3: graph representation 
  ggplot(aes(x= na_count, y = mean_exam_grade)) + geom_point() 




```

# Question 16 

```{r}
id_na_mcq <- 
  new_df |> 
  filter(str_starts(name, "MCQ")) |>
  group_by(Id) |>
  summarize(Missed = sum(is.na(value)))|>
  mutate(Missed = case_when(Missed == 0 ~ FALSE, TRUE   ~ Missed ))|>
  mutate(Missed = case_when(Missed != 0 ~ TRUE, TRUE   ~ Missed))

```

# Question 17 

```{r}

# Creation of the new dataframe with the Id, the Group and Missed grades for each student 
group_na_mcq <- data_frame(id_na_mcq, Group = grades_arranged$Group)

# Computing what was asked in the question 
percentages <- 
  group_na_mcq |>
  group_by(Group) |>
  mutate(P_missed = sum(Missed)/length(Group)) |>
  select(-Id, -Missed)|> 
  distinct()

```

# Question 18 

```{r}
#Creating the table with the average grade per group 
av_group <- 
  grades |>
  filter(!is.na(Exam))|>
  group_by(Group) |>
  summarise(mean_grade = mean(Exam))

# Creating the table that will be used for the graph 
table_graph <- inner_join(av_group, percentages)

#Graph 
ggplot(table_graph, aes(x= P_missed, y = mean_grade)) + geom_point()
```

 









